const std = @import("std");
const zig_nes_emu = @import("zig_nes_emu");

// The following code was generated by a clanker
// because I couldn't bother looking up the
// opcodes for the 6502
pub fn main(init: std.process.Init) !void {
    _ = init;
    var bus = zig_nes_emu.Bus.init();
    bus.cpu.connectBus(&bus);

    // Load a simple test program into RAM at 0x8000
    // It does 1 + 2 and stores in ram at 0x00
    // LDA #$01  (A9 01)
    // ADC #$02  (69 02)
    // STA $00   (85 00)
    // BRK       (00)
    const program = [_]u8{ 0xA9, 0x01, 0x69, 0x02, 0x85, 0x00, 0x00 };
    for (program, 0..) |byte, i| {
        bus.ram[0x8000 + i] = byte;
    }

    // Set reset vector to 0x8000
    bus.ram[0xFFFC] = 0x00;
    bus.ram[0xFFFD] = 0x80;

    // Reset the CPU
    bus.cpu.reset();

    std.debug.print("PC: 0x{X:0>4}\n", .{bus.cpu.pc});
    std.debug.print("A: 0x{X:0>2} X: 0x{X:0>2} Y: 0x{X:0>2}\n", .{ bus.cpu.a, bus.cpu.x, bus.cpu.y });
    std.debug.print("Status: 0b{b:0>8}\n", .{bus.cpu.status});

    // Run a few cycles
    for (0..20) |_| {
        bus.cpu.clock();
    }

    std.debug.print("\nAfter execution:\n", .{});
    std.debug.print("PC: 0x{X:0>4}\n", .{bus.cpu.pc});
    std.debug.print("A: 0x{X:0>2} X: 0x{X:0>2} Y: 0x{X:0>2}\n", .{ bus.cpu.a, bus.cpu.x, bus.cpu.y });
    std.debug.print("Status: 0b{b:0>8}\n", .{bus.cpu.status});
    std.debug.print("RAM[0x00]: 0x{X:0>2}\n", .{bus.ram[0x00]});
    std.debug.print("Clock count: {}\n", .{bus.cpu.clock_count});
}
